name: Install website-stalker
description: Installation of the website-stalker on a Linux host
branding:
  color: purple
  icon: box
inputs:
  version:
    description: The version of website-stalker to install
    required: true
    default: latest
  triple:
    description: The host architecture on which the executable should be running. This is the rust triple.
    required: true
    default: x86_64-unknown-linux-gnu
runs:
  using: "node16"
  main: dist/index.js
